# Generated by Django 4.2.1 on 2023-06-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Informations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=12)),
                ('Last_name', models.CharField(max_length=12)),
                ('Email', models.EmailField(max_length=40)),
                ('Phone_number', models.CharField(max_length=12)),
                ('Address1', models.CharField(max_length=102)),
                ('Product_id', models.CharField(max_length=150, blank=True))
            ],
        ),
    ]
