# Generated by Django 4.2.1 on 2023-06-21 16:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Django_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='informations',
            name='Product_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
