# Generated by Django 4.2.1 on 2023-06-21 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Django_app', '0002_informations_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informations',
            name='Product_id',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
